### PR TITLE
Fix for typescript-based code actions (#4)

### PR DESCRIPTION
**Pull request by leo-dh**
Hello there,

This addresses the problem mentioned in[ #4](https://github.com/PascalSenn/keyboard-quickfix/issues/4) where there was no action taken despite the user selecting one of the listed actions.

 It appears to be a typescript problem.  Whenever the command ``` "_typescript.applyCodeActionCommand" ``` is executed,   there is a response but there seem to be no edits made to the existing document. The fix uses the edit property returned in the earlier Command instance to make the edits.

Can anyone help to review this? Thanks!

### CODE REVIEW

**Comment by PascalSenn** [comment]
@leo-dh  thanks for pullrequest!
is this still work in progress or do you consider it done?

**Comment by leo-dh** [comment]
@PascalSenn Thanks for replying, I would consider it done with the latest commit.

**Comment by gatlee** [comment]
Just here confirming that it works! Thanks @leo-dh

**Comment by PascalSenn** [comment]
@leo-dh  sorry that it tooks so long. I forgot about it

**Pull request merged**
